// <auto-generated />
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DEVInCarContext))]
    [Migration("20221012020254_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Maça",
                            TipoID = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Alface",
                            TipoID = 2
                        });
                });

            modelBuilder.Entity("API.Models.TipoAlimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoAlimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Fruta"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Verdura"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Legume"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
